version: "3.9"
services:
  chad_auth:
    build: chad_auth
    ports:
      - "4242:8000"
    environment:
      CHAD_AUTH_APP_PROFILE: 'PROD'
      CHAD_AUTH_SUPERUSER_USERNAME: admin
      CHAD_AUTH_SUPERUSER_PASSWORD: admin
      CHAD_AUTH_SUPERUSER_EMAIL: admin@admin.local
      CHAD_AUTH_OIDC_BASE_URL: 'http://localhost:4242'